# Site settings
title: Tanjil Islam Shuvo
description: "CS student | Aspiring PHP developer | Problem-solver & data enthusiast"
baseurl: "" 
url: "https://tanjilislmsuvo.github.io"

# Author
author:
  name: "Md. Tanjil Islam Shuvo"
  email: "tanjilislmsuvo@gmail.com"

# Theme
theme: minima

# Build settings
markdown: kramdown
permalink: /:title/

# Optional plugins
plugins:
  - jekyll-feed
